# Generated by Django 3.0.3 on 2020-02-27 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of our supplier')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit card'), ('BANK_TRANSFER', 'Bank transfer')], max_length=35, verbose_name='How we will pay our supplier?')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Invoice PDF file')),
                ('invoice_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice number')),
                ('issue_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('typless_id', models.CharField(max_length=32, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to='expenses.Supplier')),
            ],
        ),
    ]
