# Generated by Django 3.0.3 on 2020-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedinvoice',
            name='confirmed',
        ),
    ]
